export const data = 
   [
    {
      transaction_id: "TXN100001",
      date: "2025-03-01",
      time: "14:23:45",
      amount: 258,
      currency: "USD",
      status: "Completed",
      sender: "John Doe",
      receiver: "Alice Smith",
      payment_method: "Credit Card",
      category: "Shopping",
    },
    {
      transaction_id: "TXN100002",
      date: "2025-03-02",
      time: "10:05:32",
      amount: 75,
      currency: "USD",
      status: "Pending",
      sender: "Emily Davis",
      receiver: "David Johnson",
      payment_method: "PayPal",
      category: "Food & Dining",
    },
    {
      transaction_id: "TXN100003",
      date: "2025-03-03",
      time: "18:45:12",
      amount: 503,
      currency: "USD",
      status: "Failed",
      sender: "Michael Brown",
      receiver: "Sarah Wilson",
      payment_method: "Bank Transfer",
      category: "Electronics",
    },
    {
      transaction_id: "TXN100004",
      date: "2025-03-04",
      time: "09:12:22",
      amount: 29,
      currency: "USD",
      status: "Completed",
      sender: "Chris Martin",
      receiver: "Emma Thompson",
      payment_method: "Debit Card",
      category: "Transportation",
    },
    {
      transaction_id: "TXN100005",
      date: "2025-03-05",
      time: "22:30:15",
      amount: 150,
      currency: "USD",
      status: "Completed",
      sender: "Sophia Roberts",
      receiver: "Olivia White",
      payment_method: "Crypto",
      category: "Entertainment",
    },
    {
      transaction_id: "TXN100006",
      date: "2025-03-06",
      time: "08:55:50",
      amount: 321,
      currency: "USD",
      status: "Pending",
      sender: "Liam Scott",
      receiver: "William Hall",
      payment_method: "Wire Transfer",
      category: "Travel",
    },
    {
      transaction_id: "TXN100007",
      date: "2025-03-07",
      time: "16:42:38",
      amount: 95.6,
      currency: "USD",
      status: "Completed",
      sender: "Isabella Wright",
      receiver: "Benjamin Harris",
      payment_method: "Google Pay",
      category: "Groceries",
    },
    {
      transaction_id: "TXN100008",
      date: "2025-03-08",
      time: "11:18:29",
      amount: 401,
      currency: "USD",
      status: "Failed",
      sender: "James Lewis",
      receiver: "Charlotte King",
      payment_method: "Venmo",
      category: "Bills & Utilities",
    },
    {
      transaction_id: "TXN100009",
      date: "2025-03-09",
      time: "20:05:14",
      amount: 273,
      currency: "USD",
      status: "Completed",
      sender: "Ethan Walker",
      receiver: "Mia Allen",
      payment_method: "Apple Pay",
      category: "Health & Wellness",
    },
    {
      transaction_id: "TXN100010",
      date: "2025-03-10",
      time: "13:30:10",
      amount: 186,
      currency: "USD",
      status: "Completed",
      sender: "Ava Martinez",
      receiver: "Noah Clark",
      payment_method: "CashApp",
      category: "Education",
    },
  ]
